version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Idea@2025
      MYSQL_DATABASE: University
    ports:
      - "3306:3306"
    networks:
      - springnet

  app:
    image: fahaddock/myapp:latest
    container_name: springboot_myapp
    restart: always
    depends_on:
      - db
    ports:
      - "9988:9988"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/University
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Idea@2025
    networks:
      - springnet

networks:
  springnet:
